---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: wireguard-kmod-driver-container
  name: wireguard-kmod-driver-container
  namespace: tigera-wireguard-kmod
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: wireguard-kmod-driver-build
  name: wireguard-kmod-driver-build
  namespace: tigera-wireguard-kmod
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  runPolicy: "Serial"
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
  source:
    configMaps:
    - configMap:
        name: wireguard-kmod-helpers
    dockerfile: |
      FROM quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0661d0560654e7e2d1761e883ffdd6c482c8c8f37e60608bb59c44fa81a3f0bb

      ARG KMODVER
      ARG ARTIFACTS_LOCATION
      ARG WIREGUARD_ARCHIVE_NAME
      ARG WIREGUARD_ARCHIVE_SHA256


      WORKDIR /
      RUN cat /etc/systemd/system/kmod*
      RUN echo "Downloading ${ARTIFACTS_LOCATION}/${WIREGUARD_ARCHIVE_NAME}.tar.xz (${WIREGUARD_ARCHIVE_SHA256})" &&            \
        curl -LS ${ARTIFACTS_LOCATION}/${WIREGUARD_ARCHIVE_NAME}.tar.xz |                                                       \
        { t="$(mktemp)"; trap "rm -f '$t'" INT TERM EXIT; cat >| "$t"; sha256sum --quiet -c <<<"${WIREGUARD_ARCHIVE_SHA256} $t" \
        || exit 1; cat "$t"; } | tar xJf -

      RUN make -C ${WIREGUARD_ARCHIVE_NAME}/src -j$(nproc) KERNELRELEASE=$(uname -r)  \
      && make -C ${WIREGUARD_ARCHIVE_NAME}/src install KERNELRELEASE=$(uname -r)      \
      && rm -rf ${WIREGUARD_ARCHIVE_NAME}


      WORKDIR /etc/wireguard
      ADD wireguard-kmod-load.sh .
      ADD wireguard-kmod-reload.sh .
      ADD wireguard-kmod-unload.sh .
      ADD wireguard-kmod.conf .
      RUN chmod +x wireguard-kmod-*.sh
      ADD wireguard.service /etc/systemd/system/wireguard.service

      RUN systemctl enable wireguard.service

      CMD /sbin/init
  strategy:
    dockerStrategy:
      buildArgs:
        - name: KMODVER
          value: "1.0.20210606"
        - name: WIREGUARD_ARCHIVE_NAME
          value: "wireguard-linux-compat-1.0.20210606"
        - name: WIREGUARD_ARCHIVE_SHA256
          value: "3f5d990006e6eabfd692d925ec314fff2c5ee7dcdb869a6510d579acfdd84ec0"
        - name: ARTIFACTS_LOCATION
          value: "https://seth-wireguard-ocp-kr-pub.s3.us-west-2.amazonaws.com"
  output:
    to:
      kind: ImageStreamTag
      name: wireguard-kmod-driver-container:latest